#!/bin/sh

day=`date +%d`
mkdir $day
cd $day
touch input example
ln -s ../starter.py starter.py
for i in 1 2
do
        if [ ! -s $i.py ]
        then
                echo "from starter import get_puzzle_input" > $i.py
                echo "import pdb" >> $i.py
        fi
done
